name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "services/users/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: |
          go get ./
          go build
        working-directory: ./services/users
